#!/bin/bash
echo "=== 系统最终状态 ==="
echo ""
echo "【前端】http://localhost:3017"
curl -s -o /dev/null -w "状态码: %{http_code}\n" http://localhost:3017
echo ""
echo "【后端】http://localhost:8080/api"
curl -s -o /dev/null -w "状态码: %{http_code}\n" http://localhost:8080/api/auth/login -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"admin123"}'
echo ""
echo "【AI】http://localhost:11434"
curl -s http://localhost:11434/api/tags | grep -q "qwen" && echo "✅ Ollama AI运行中(qwen3:8b)" || echo "❌ AI未启动"
echo ""
echo "【登录账号】"
echo "账号: admin"
echo "密码: admin123"
echo ""
echo "【本次开发完成】"
echo "1. ✅ AI Prompt优化为中文"
echo "2. ✅ 案件创建异常处理"
echo "3. ✅ 权限检查优化"
echo "4. ✅ 前端服务重启"
echo ""
echo "【建议】"
echo "请在浏览器中测试以下功能："
echo "1. 创建中文案件"
echo "2. 案件详情页跳转"
echo "3. AI知识问答"
echo "4. 视图切换(列表/看板)"
