package com.lawfirm.service;

import com.lawfirm.dto.*;
import com.lawfirm.entity.*;
import com.lawfirm.enums.CaseStatus;
import com.lawfirm.exception.DuplicateResourceException;
import com.lawfirm.exception.InvalidParameterException;
import com.lawfirm.exception.ResourceNotFoundException;
import com.lawfirm.repository.*;
import com.lawfirm.util.CaseFeeFormatter;
import com.lawfirm.util.PageResult;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lawfirm.vo.CaseDetailVO;
import com.lawfirm.vo.CaseListVO;
import org.springframework.beans.BeanUtils;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 案件服务
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class CaseService {

    private static final Set<String> SUPPORTED_CASE_TYPES = Set.of(
            "CIVIL", "ARBITRATION", "CRIMINAL", "ADMINISTRATIVE", "NON_LITIGATION", "CONSULTANT");

    private final CaseRepository caseRepository;
    private final PartyService partyService;
    private final CaseProcedureService caseProcedureService;
    private final CaseRecordService caseRecordService;
    private final CaseTimelineService caseTimelineService;
    private final CaseMemberService caseMemberService;
    private final CaseStageService caseStageService;
    private final UserRepository userRepository;
    private final UserRoleRepository userRoleRepository;
    private final RoleRepository roleRepository;
    private final CaseMemberRepository caseMemberRepository;
    private final FinanceRecordService financeRecordService;
    private final TodoService todoService;
    private final ClientService clientService;
    private final ClientRepository clientRepository;
    private final ApprovalService approvalService;
    private final ObjectMapper objectMapper;
    private final UserPermissionService userPermissionService;

    /**
     * 创建案件
     */
    @Transactional(rollbackFor = Exception.class)
    public CaseDetailVO createCase(CaseCreateRequest request, Long currentUserId) {
        // 参数校验
        if (request.getCaseType() == null) {
            throw new InvalidParameterException("caseType", "案件类型不能为空");
        }
        if (request.getProcedure() == null) {
            throw new InvalidParameterException("procedure", "案件程序不能为空");
        }
        if (request.getOwnerId() == null) {
            throw new InvalidParameterException("ownerId", "主办律师不能为空");
        }
        hydrateConsultantClient(request, currentUserId);
        validateFilingRequest(request);

        // 查重检查
        if (request.getCaseNumber() != null && !request.getCaseNumber().trim().isEmpty()) {
            if (caseRepository.existsByCaseNumberAndDeletedFalse(request.getCaseNumber())) {
                throw new DuplicateResourceException("案件", "caseNumber", request.getCaseNumber());
            }
        }

        // 1. 创建案件基本信息
        Case caseEntity = new Case();

        // 自动生成案件名称
        if (request.getCaseName() == null || request.getCaseName().trim().isEmpty()) {
            caseEntity.setCaseName(autoGenerateName(request));
        } else {
            caseEntity.setCaseName(request.getCaseName());
        }

        // 申请阶段使用临时编号，审批通过后由行政流程生成正式合同号
        if (request.getCaseNumber() == null || request.getCaseNumber().trim().isEmpty()) {
            caseEntity.setCaseNumber(autoGenerateDraftNumber(request.getCaseType()));
        } else {
            caseEntity.setCaseNumber(request.getCaseNumber());
        }

        caseEntity.setCaseType(request.getCaseType());
        caseEntity.setProcedure(request.getProcedure());
        caseEntity.setCaseReason(request.getCaseReason());
        caseEntity.setCourt(request.getCourt());
        caseEntity.setAcceptanceDate(request.getAcceptanceDate() != null ? request.getAcceptanceDate() : LocalDate.now());
        // 立案日期由主任终审通过时写入，申请人不得预填。
        caseEntity.setFilingDate(null);
        caseEntity.setDeadlineDate(request.getDeadlineDate());
        caseEntity.setCommissionDate(request.getCommissionDate());
        caseEntity.setSuspectName(request.getSuspectName());
        caseEntity.setSubjectMatter(request.getSubjectMatter());
        caseEntity.setBusinessType(request.getBusinessType());
        caseEntity.setAgencyType(request.getAgencyType());
        caseEntity.setServiceStartDate(request.getServiceStartDate());
        caseEntity.setServiceEndDate(request.getServiceEndDate());
        caseEntity.setConsultantUnitName(request.getConsultantUnitName());
        caseEntity.setConsultantContactName(request.getConsultantContactName());
        caseEntity.setConsultantContactDepartment(request.getConsultantContactDepartment());
        caseEntity.setConsultantContactTitle(request.getConsultantContactTitle());
        caseEntity.setConsultantContactPhone(request.getConsultantContactPhone());
        caseEntity.setConsultantContactEmail(request.getConsultantContactEmail());
        caseEntity.setConsultantServiceScope(request.getConsultantServiceScope());
        caseEntity.setConsultantResponseRequirement(request.getConsultantResponseRequirement());
        caseEntity.setConsultantIncludedServices(request.getConsultantIncludedServices());
        caseEntity.setConsultantExcludedServices(request.getConsultantExcludedServices());
        caseEntity.setRenewalReminderDate(request.getRenewalReminderDate());
        caseEntity.setTrialStages(request.getTrialStages());
        caseEntity.setCourtCaseNumber(request.getCourtCaseNumber());
        caseEntity.setHearingDate(request.getHearingDate());
        caseEntity.setTags(request.getTags());
        caseEntity.setSummary(request.getSummary());
        caseEntity.setLevel(hasText(request.getLevel()) ? request.getLevel() : "GENERAL");
        caseEntity.setAmount(request.getAmount());
        caseEntity.setAttorneyFee(request.getAttorneyFee());
        caseEntity.setFeeMethod(request.getFeeMethod());
        caseEntity.setRiskRatio(request.getRiskRatio());
        caseEntity.setRiskFee(request.getRiskFee());
        caseEntity.setFeeNotes(request.getFeeNotes());
        caseEntity.setFreeReason(request.getFreeReason());
        caseEntity.setAllocationJson(request.getAllocationJson());

        // 设置初始状态：新建案件进入立案审批流程，审批通过后才转为正式在办案件
        caseEntity.setStatus(CaseStatus.PENDING_APPROVAL.getCode());
        caseEntity.setOwnerId(request.getOwnerId());
        caseEntity.setClientId(resolvePrimaryClientId(request));

        // 保存案件
        caseEntity = caseRepository.save(caseEntity);
        log.info("[DEBUG] Case saved: id={}, deadlineDate={}", caseEntity.getId(), caseEntity.getDeadlineDate());

        // 在写入本案当事人前完成委托方初筛，避免本案自身被误判为历史命中。
        int conflictCheckCount = createFilingConflictChecks(request, caseEntity.getId(), currentUserId);

        // 2. 创建当事人
        List<Party> parties = partyService.batchCreate(request.getParties(), caseEntity.getId());

        // 2.1 同步创建客户（如果勾选了"同步创建客户"）
        syncPartiesToClients(request.getParties(), caseEntity.getId(), currentUserId);

        // 3. 添加团队成员
        caseMemberService.addMember(caseEntity.getId(), request.getOwnerId(), "OWNER");
        if (request.getCoOwnerIds() != null && !request.getCoOwnerIds().isEmpty()) {
            caseMemberService.addMembers(caseEntity.getId(), request.getCoOwnerIds(), "CO_OWNER");
        }
        if (request.getAssistantIds() != null && !request.getAssistantIds().isEmpty()) {
            caseMemberService.addMembers(caseEntity.getId(), request.getAssistantIds(), "ASSISTANT");
        }

        // 4. 创建案件阶段流程
        caseStageService.initializeStages(caseEntity.getId(), request.getCaseType());

        // 5. 如果有审限时间，自动生成审限届满待办。阶段待办由 CaseStageService
        // 在阶段进入时按类型生成，避免新建案件一次性产生全部未来任务。
        log.info("[DEBUG] Checking deadline: caseId={}, deadlineDate={}, isNull={}",
                caseEntity.getId(), caseEntity.getDeadlineDate(), caseEntity.getDeadlineDate() == null);
        if (caseEntity.getDeadlineDate() != null) {
            createDeadlineTodo(caseEntity);
        } else {
            log.info("[DEBUG] deadlineDate is null, skipping deadline todo creation");
        }

        // 6. 记录动态
        caseTimelineService.createSystemTimeline(
                caseEntity.getId(),
                "CASE_FILING_SUBMITTED",
                "立案申请已提交，案号：" + caseEntity.getCaseNumber()
                        + (conflictCheckCount > 0 ? "；已生成 " + conflictCheckCount + " 份待行政复核的利冲初筛记录" : "；未识别到委托方，需行政补充利冲审查")
        );

        submitCaseFilingApproval(caseEntity, currentUserId);

        // 7. 创建应收款记录（如果有）
        if (request.getReceivables() != null && !request.getReceivables().isEmpty()) {
            final Long caseId = caseEntity.getId();
            request.getReceivables().forEach(receivable -> {
                FinanceRecordDTO financeRecordDTO = new FinanceRecordDTO();
                financeRecordDTO.setCaseId(caseId);
                financeRecordDTO.setFinanceType("RECEIVABLE");
                financeRecordDTO.setAmount(receivable.getAmount());
                financeRecordDTO.setTransactionDate(LocalDate.parse(receivable.getDueDate()));
                financeRecordDTO.setDescription(receivable.getName() + (receivable.getNotes() != null ? " - " + receivable.getNotes() : ""));
                financeRecordService.createFinanceRecord(financeRecordDTO, currentUserId);
            });
            log.info("创建应收款记录：{}条", request.getReceivables().size());
        }

        return getCaseDetail(caseEntity.getId());
    }

    private void validateFilingRequest(CaseCreateRequest request) {
        if (!SUPPORTED_CASE_TYPES.contains(request.getCaseType())) {
            throw new InvalidParameterException("caseType", "不支持的案件类型");
        }
        if ("CRIMINAL".equals(request.getCaseType()) && !hasText(request.getSuspectName())) {
            throw new InvalidParameterException("suspectName", "刑事案件犯罪嫌疑人不能为空");
        }
        if ("CONSULTANT".equals(request.getCaseType())) {
            if (!hasText(request.getConsultantUnitName())) {
                throw new InvalidParameterException("consultantUnitName", "顾问单位不能为空");
            }
            if (request.getServiceStartDate() == null) {
                throw new InvalidParameterException("serviceStartDate", "顾问案件合同服务开始时间不能为空");
            }
            if (request.getServiceEndDate() == null) {
                throw new InvalidParameterException("serviceEndDate", "顾问案件合同服务结束时间不能为空");
            }
            if (request.getServiceStartDate().isAfter(request.getServiceEndDate())) {
                throw new InvalidParameterException("serviceEndDate", "顾问服务结束时间不能早于开始时间");
            }
        }
        if ("FIXED".equals(request.getFeeMethod()) || "BASE_PLUS_CONTINGENT".equals(request.getFeeMethod())) {
            if (request.getAttorneyFee() == null || request.getAttorneyFee().compareTo(BigDecimal.ZERO) <= 0) {
                throw new InvalidParameterException("attorneyFee", "固定收费或基础+风险收费案件代理金额不能为空");
            }
        }
        if (isRiskFee(request.getFeeMethod())) {
            boolean hasRiskFee = request.getRiskFee() != null && request.getRiskFee().compareTo(BigDecimal.ZERO) > 0;
            boolean hasRiskRatio = request.getRiskRatio() != null && request.getRiskRatio().compareTo(BigDecimal.ZERO) > 0;
            if (!hasRiskFee && !hasRiskRatio) {
                throw new InvalidParameterException("riskFee", "风险收费案件请填写风险费用或风险比例");
            }
            if (request.getRiskRatio() != null && request.getRiskRatio().compareTo(new BigDecimal("18")) > 0) {
                throw new InvalidParameterException("riskRatio", "请检查风险代理收费比例是否合规，风险比例不得超过18%");
            }
        }
        if ("FREE".equals(request.getFeeMethod()) && !hasText(request.getFreeReason())) {
            throw new InvalidParameterException("freeReason", "免费代理案件必须填写免费理由");
        }
        validateAllocation(request.getAllocationJson());
    }

    private void hydrateConsultantClient(CaseCreateRequest request, Long currentUserId) {
        if (!"CONSULTANT".equals(request.getCaseType()) || request.getConsultantClientId() == null) {
            return;
        }
        clientService.assertClientVisible(request.getConsultantClientId(), currentUserId);
        Client client = clientRepository.findById(request.getConsultantClientId())
                .filter(item -> !Boolean.TRUE.equals(item.getDeleted()))
                .orElseThrow(() -> new InvalidParameterException("consultantClientId", "顾问单位客户不存在"));
        if ("个人".equals(client.getClientType())) {
            throw new InvalidParameterException("consultantClientId", "顾问单位不能选择个人客户");
        }
        request.setConsultantUnitName(client.getClientName());
        if (request.getClientIds() == null || request.getClientIds().isEmpty()) {
            request.setClientIds(Collections.singletonList(client.getId()));
        }
    }

    private Long resolvePrimaryClientId(CaseCreateRequest request) {
        if ("CONSULTANT".equals(request.getCaseType()) && request.getConsultantClientId() != null) {
            return request.getConsultantClientId();
        }
        if (request.getClientIds() == null || request.getClientIds().isEmpty()) return null;
        return request.getClientIds().get(0);
    }

    private int createFilingConflictChecks(CaseCreateRequest request, Long caseId, Long currentUserId) {
        Map<String, ClientDTO> subjects = new LinkedHashMap<>();
        if (request.getParties() != null) {
            request.getParties().stream()
                    .filter(Objects::nonNull)
                    .filter(party -> Boolean.TRUE.equals(party.getIsClient()))
                    .filter(party -> hasText(party.getName()))
                    .forEach(party -> {
                        ClientDTO dto = new ClientDTO();
                        dto.setClientName(party.getName().trim());
                        dto.setClientType("ORGANIZATION".equalsIgnoreCase(party.getPartyType()) ? "单位" : "个人");
                        dto.setClientRelationship("委托人");
                        dto.setClientRole(party.getPartyRole());
                        dto.setIdCard(party.getIdCard());
                        dto.setCreditCode(party.getCreditCode());
                        subjects.putIfAbsent(dto.getClientName().toLowerCase(Locale.ROOT), dto);
                    });
        }

        if (subjects.isEmpty()) {
            Long primaryClientId = resolvePrimaryClientId(request);
            if (primaryClientId != null) {
                clientRepository.findById(primaryClientId)
                        .filter(client -> !Boolean.TRUE.equals(client.getDeleted()))
                        .ifPresent(client -> {
                            ClientDTO dto = new ClientDTO();
                            dto.setClientName(client.getClientName());
                            dto.setClientType(client.getClientType());
                            dto.setClientRelationship(client.getClientRelationship());
                            dto.setClientRole(client.getClientRole());
                            dto.setIdCard(client.getIdCard());
                            dto.setCreditCode(client.getCreditCode());
                            subjects.put(dto.getClientName().trim().toLowerCase(Locale.ROOT), dto);
                        });
            }
        }

        subjects.values().forEach(subject ->
                clientService.checkConflictPreviewAndRecord(subject, currentUserId, caseId));
        return subjects.size();
    }

    private void validateAllocation(String allocationJson) {
        if (!hasText(allocationJson)) {
            throw new InvalidParameterException("allocationJson", "分配情况不能为空");
        }
        try {
            JsonNode node = objectMapper.readTree(allocationJson);
            BigDecimal sourceRatio = decimalValue(node, "sourceRatio");
            BigDecimal departmentRatio = decimalValue(node, "departmentRatio");
            BigDecimal firmRatio = decimalValue(node, "firmRatio");
            BigDecimal total = sourceRatio.add(departmentRatio).add(firmRatio);
            if (total.compareTo(new BigDecimal("100")) != 0) {
                throw new InvalidParameterException("allocationJson", "案源比例、部门比例、律所比例合计必须等于100%");
            }
        } catch (InvalidParameterException e) {
            throw e;
        } catch (Exception e) {
            throw new InvalidParameterException("allocationJson", "分配情况格式不正确");
        }
    }

    private BigDecimal decimalValue(JsonNode node, String field) {
        JsonNode value = node.get(field);
        if (value == null || value.isNull()) {
            return BigDecimal.ZERO;
        }
        return new BigDecimal(value.asText("0"));
    }

    private boolean isRiskFee(String feeMethod) {
        return "CONTINGENT".equals(feeMethod)
                || "BASE_PLUS_CONTINGENT".equals(feeMethod)
                || "FIXED_PLUS_CONTINGENT".equals(feeMethod);
    }

    private void submitCaseFilingApproval(Case caseEntity, Long currentUserId) {
        Long approverId = userPermissionService.findFirstActiveUserByPermission(
                        "CASE_FILING_REVIEW", "CASE_FILING_ADMIN")
                .map(User::getId)
                .orElse(null);
        if (approverId == null) {
            caseTimelineService.createSystemTimeline(
                    caseEntity.getId(),
                    "CASE_FILING_APPROVER_MISSING",
                    "未找到具有立案行政初审权限的账号，请在角色权限中配置后重新提交"
            );
            return;
        }

        ApprovalCreateRequest approvalRequest = new ApprovalCreateRequest();
        approvalRequest.setApprovalType(ApprovalService.TYPE_CASE_FILING);
        approvalRequest.setTitle("立案审批：" + caseEntity.getCaseName());
        approvalRequest.setContent(buildFilingApprovalContent(caseEntity));
        approvalRequest.setCaseId(caseEntity.getId());
        approvalRequest.setCurrentApproverId(approverId);
        approvalService.createApproval(approvalRequest, currentUserId);

        caseTimelineService.createSystemTimeline(
                caseEntity.getId(),
                "CASE_FILING_APPROVAL_CREATED",
                "立案审批已流转至行政管理：" + getUserName(approverId)
        );
    }

    private String buildFilingApprovalContent(Case caseEntity) {
        return "请进行利冲审查并在审批意见中填写审查结论。"
                + "\n案件名称：" + caseEntity.getCaseName()
                + "\n案号：" + caseEntity.getCaseNumber()
                + "\n案件类型：" + getCaseTypeDesc(caseEntity.getCaseType())
                + "\n业务类型：" + (caseEntity.getBusinessType() == null ? "" : caseEntity.getBusinessType())
                + "\n案由：" + (caseEntity.getCaseReason() == null ? "" : caseEntity.getCaseReason())
                + "\n收费方式：" + CaseFeeFormatter.format(caseEntity)
                + "\n主办律师：" + getUserName(caseEntity.getOwnerId());
    }

    /**
     * 更新案件
     */
    @Transactional(rollbackFor = Exception.class)
    public CaseDetailVO updateCase(Long caseId, CaseUpdateRequest request) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        rejectWorkflowControlledUpdates(request);

        if (request.getCaseType() != null && !request.getCaseType().equals(caseEntity.getCaseType())) {
            throw new InvalidParameterException("caseType", "案件类型建立后不可直接变更，以免既有流程和文件目录失配");
        }

        // 更新基本信息
        if (request.getCaseName() != null) {
            caseEntity.setCaseName(request.getCaseName());
        }
        if (request.getCaseType() != null) {
            caseEntity.setCaseType(request.getCaseType());
        }
        if (request.getProcedure() != null) {
            caseEntity.setProcedure(request.getProcedure());
        }
        if (request.getCaseReason() != null) {
            caseEntity.setCaseReason(request.getCaseReason());
        }
        if (request.getCourt() != null) {
            caseEntity.setCourt(request.getCourt());
        }
        if (request.getAcceptanceDate() != null) {
            caseEntity.setAcceptanceDate(request.getAcceptanceDate());
        }
        if (request.getDeadlineDate() != null) {
            caseEntity.setDeadlineDate(request.getDeadlineDate());
        }
        if (request.getCommissionDate() != null) {
            caseEntity.setCommissionDate(request.getCommissionDate());
        }
        if (request.getSuspectName() != null) caseEntity.setSuspectName(request.getSuspectName());
        if (request.getSubjectMatter() != null) caseEntity.setSubjectMatter(request.getSubjectMatter());
        if (request.getBusinessType() != null) caseEntity.setBusinessType(request.getBusinessType());
        if (request.getAgencyType() != null) caseEntity.setAgencyType(request.getAgencyType());
        if (request.getServiceStartDate() != null) caseEntity.setServiceStartDate(request.getServiceStartDate());
        if (request.getServiceEndDate() != null) caseEntity.setServiceEndDate(request.getServiceEndDate());
        if (request.getConsultantClientId() != null) caseEntity.setClientId(request.getConsultantClientId());
        if (request.getConsultantUnitName() != null) caseEntity.setConsultantUnitName(request.getConsultantUnitName());
        if (request.getConsultantContactName() != null) caseEntity.setConsultantContactName(request.getConsultantContactName());
        if (request.getConsultantContactDepartment() != null) caseEntity.setConsultantContactDepartment(request.getConsultantContactDepartment());
        if (request.getConsultantContactTitle() != null) caseEntity.setConsultantContactTitle(request.getConsultantContactTitle());
        if (request.getConsultantContactPhone() != null) caseEntity.setConsultantContactPhone(request.getConsultantContactPhone());
        if (request.getConsultantContactEmail() != null) caseEntity.setConsultantContactEmail(request.getConsultantContactEmail());
        if (request.getConsultantServiceScope() != null) caseEntity.setConsultantServiceScope(request.getConsultantServiceScope());
        if (request.getConsultantResponseRequirement() != null) caseEntity.setConsultantResponseRequirement(request.getConsultantResponseRequirement());
        if (request.getConsultantIncludedServices() != null) caseEntity.setConsultantIncludedServices(request.getConsultantIncludedServices());
        if (request.getConsultantExcludedServices() != null) caseEntity.setConsultantExcludedServices(request.getConsultantExcludedServices());
        if (request.getRenewalReminderDate() != null) caseEntity.setRenewalReminderDate(request.getRenewalReminderDate());
        if (request.getTrialStages() != null) caseEntity.setTrialStages(request.getTrialStages());
        if (request.getCourtCaseNumber() != null) caseEntity.setCourtCaseNumber(request.getCourtCaseNumber());
        if (request.getHearingDate() != null) caseEntity.setHearingDate(request.getHearingDate());
        if (request.getTags() != null) {
            caseEntity.setTags(request.getTags());
        }
        if (request.getSummary() != null) {
            caseEntity.setSummary(request.getSummary());
        }
        if (request.getLevel() != null) {
            caseEntity.setLevel(request.getLevel());
        }
        if (request.getAmount() != null) {
            caseEntity.setAmount(request.getAmount());
        }
        if (request.getAttorneyFee() != null) {
            caseEntity.setAttorneyFee(request.getAttorneyFee());
        }
        if (request.getFeeMethod() != null) {
            caseEntity.setFeeMethod(request.getFeeMethod());
        }
        if (request.getRiskRatio() != null) caseEntity.setRiskRatio(request.getRiskRatio());
        if (request.getRiskFee() != null) caseEntity.setRiskFee(request.getRiskFee());
        if (request.getFeeNotes() != null) caseEntity.setFeeNotes(request.getFeeNotes());
        if (request.getFreeReason() != null) caseEntity.setFreeReason(request.getFreeReason());
        if (request.getAllocationJson() != null) caseEntity.setAllocationJson(request.getAllocationJson());
        if (request.getWonAmount() != null) {
            caseEntity.setWonAmount(request.getWonAmount());
        }
        if (request.getActualReceived() != null) {
            caseEntity.setActualReceived(request.getActualReceived());
        }
        // 更新主办律师
        if (request.getOwnerId() != null && !request.getOwnerId().equals(caseEntity.getOwnerId())) {
            caseMemberService.updateMemberType(caseId, caseEntity.getOwnerId(), "CO_OWNER");
            caseMemberService.updateMemberType(caseId, request.getOwnerId(), "OWNER");
            caseEntity.setOwnerId(request.getOwnerId());
        }

        // 更新协办律师和助理
        if (request.getCoOwnerIds() != null) {
            // 先移除所有协办律师
            List<CaseMember> existingCoOwners = caseMemberService.getByCaseIdAndType(caseEntity.getId(), "CO_OWNER");
            existingCoOwners.forEach(member -> caseMemberService.removeMember(caseEntity.getId(), member.getUserId()));
            if (!request.getCoOwnerIds().isEmpty()) {
                caseMemberService.addMembers(caseEntity.getId(), request.getCoOwnerIds(), "CO_OWNER");
            }
            log.info("更新协办律师：{}人", request.getCoOwnerIds().size());
        }
        if (request.getAssistantIds() != null) {
            // 先移除所有助理
            List<CaseMember> existingAssistants = caseMemberService.getByCaseIdAndType(caseEntity.getId(), "ASSISTANT");
            existingAssistants.forEach(member -> caseMemberService.removeMember(caseEntity.getId(), member.getUserId()));
            if (!request.getAssistantIds().isEmpty()) {
                caseMemberService.addMembers(caseEntity.getId(), request.getAssistantIds(), "ASSISTANT");
            }
            log.info("更新助理：{}人", request.getAssistantIds().size());
        }

        validateUpdatedCase(caseEntity, request);

        caseRepository.save(caseEntity);

        // 更新当事人（全量更新：删除旧的，添加新的）
        if (request.getParties() != null && !request.getParties().isEmpty()) {
            // 获取现有当事人并逻辑删除
            List<com.lawfirm.vo.PartyVO> existingParties = partyService.getByCaseId(caseEntity.getId());
            existingParties.forEach(partyVO -> {
                if (partyVO.getId() != null) {
                    partyService.delete(partyVO.getId());
                }
            });
            // 批量创建新当事人
            partyService.batchCreate(request.getParties(), caseEntity.getId());
            log.info("更新当事人：{}人", request.getParties().size());
        }

        // 记录动态
        caseTimelineService.createSystemTimeline(
                caseId,
                "CASE_UPDATED",
                "案件信息已更新"
        );

        return getCaseDetail(caseId);
    }

    private void rejectWorkflowControlledUpdates(CaseUpdateRequest request) {
        if (hasText(request.getStatus()) || hasText(request.getCurrentStage())) {
            throw new InvalidParameterException("案件状态和办理阶段必须通过专用流程变更");
        }
        if (request.getFilingDate() != null) {
            throw new InvalidParameterException("立案时间由立案终审通过时间自动确定");
        }
        if (request.getCloseStatus() != null || request.getCloseDate() != null) {
            throw new InvalidParameterException("结案信息必须通过结案流程登记");
        }
        if (request.getArchiveDate() != null || request.getArchiveLocation() != null) {
            throw new InvalidParameterException("归档信息必须通过智能归档流程登记");
        }
    }

    private void validateUpdatedCase(Case caseEntity, CaseUpdateRequest request) {
        if (!SUPPORTED_CASE_TYPES.contains(caseEntity.getCaseType())) {
            throw new InvalidParameterException("caseType", "不支持的案件类型");
        }
        if ("CRIMINAL".equals(caseEntity.getCaseType()) && request.getSuspectName() != null
                && !hasText(caseEntity.getSuspectName())) {
            throw new InvalidParameterException("suspectName", "刑事案件犯罪嫌疑人/被告人不能为空");
        }
        boolean consultantFieldsChanged = request.getConsultantUnitName() != null
                || request.getServiceStartDate() != null || request.getServiceEndDate() != null;
        if ("CONSULTANT".equals(caseEntity.getCaseType()) && consultantFieldsChanged) {
            if (!hasText(caseEntity.getConsultantUnitName())) {
                throw new InvalidParameterException("consultantUnitName", "顾问单位不能为空");
            }
            if (caseEntity.getServiceStartDate() == null || caseEntity.getServiceEndDate() == null) {
                throw new InvalidParameterException("serviceStartDate", "顾问案件服务期限不能为空");
            }
            if (caseEntity.getServiceStartDate().isAfter(caseEntity.getServiceEndDate())) {
                throw new InvalidParameterException("serviceEndDate", "顾问服务结束时间不能早于开始时间");
            }
        }
    }

    /**
     * 获取案件列表
     */
    @Transactional(readOnly = true)
    public PageResult<CaseListVO> getCaseList(CaseQueryRequest request, Long currentUserId) {
        LocalDate startDate = parseQueryDate(request.getStartDate(), "startDate");
        LocalDate endDate = parseQueryDate(request.getEndDate(), "endDate");
        if (startDate != null && endDate != null && startDate.isAfter(endDate)) {
            throw new InvalidParameterException("dateRange", "开始日期不能晚于结束日期");
        }
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        boolean hasAllCaseViewAccess = hasAllCaseViewAccess(currentUser);
        boolean hasDepartmentCaseViewAccess = !hasAllCaseViewAccess && isDepartmentManager(currentUser);
        List<Long> visibleUserIds = hasAllCaseViewAccess
                ? Collections.emptyList()
                : (hasDepartmentCaseViewAccess ? getDepartmentScopedUserIds(currentUser) : Collections.singletonList(currentUserId));
        List<Long> visibleCaseIds = hasAllCaseViewAccess ? Collections.emptyList() : getDepartmentScopedCaseIds(visibleUserIds);
        List<Long> filterDepartmentUserIds = request.getDepartmentId() == null
                ? Collections.emptyList()
                : getActiveUserIdsByDepartment(request.getDepartmentId());
        List<Long> filterDepartmentCaseIds = request.getDepartmentId() == null
                ? Collections.emptyList()
                : getDepartmentScopedCaseIds(filterDepartmentUserIds);

        // 构建查询条件（接口统一使用0基页码）
        Pageable pageable = PageRequest.of(
                Math.max(0, request.getPage()),
                request.getSize(),
                Sort.by(Sort.Direction.fromString(request.getSortDirection()), request.getSortField())
        );

        // 构建动态查询
        Specification<Case> spec = (root, query, cb) -> {
            List<javax.persistence.criteria.Predicate> predicates = new ArrayList<>();

            if (!hasAllCaseViewAccess) {
                List<javax.persistence.criteria.Predicate> accessPredicates = new ArrayList<>();
                if (!visibleUserIds.isEmpty()) {
                    accessPredicates.add(root.get("ownerId").in(visibleUserIds));
                }
                if (!visibleCaseIds.isEmpty()) {
                    accessPredicates.add(root.get("id").in(visibleCaseIds));
                }
                if (accessPredicates.isEmpty()) {
                    predicates.add(cb.disjunction());
                } else {
                    predicates.add(cb.or(accessPredicates.toArray(new javax.persistence.criteria.Predicate[0])));
                }
            }

            // 基础条件
            if (hasText(request.getCaseType())) {
                predicates.add(cb.equal(root.get("caseType"), request.getCaseType()));
            }
            if (hasText(request.getStatus())) {
                predicates.add(cb.equal(root.get("status"), request.getStatus()));
            }
            if (hasText(request.getCaseReason())) {
                predicates.add(cb.like(root.get("caseReason"), "%" + request.getCaseReason().trim() + "%"));
            }
            if (request.getDepartmentId() != null) {
                List<javax.persistence.criteria.Predicate> departmentPredicates = new ArrayList<>();
                if (!filterDepartmentUserIds.isEmpty()) {
                    departmentPredicates.add(root.get("ownerId").in(filterDepartmentUserIds));
                }
                if (!filterDepartmentCaseIds.isEmpty()) {
                    departmentPredicates.add(root.get("id").in(filterDepartmentCaseIds));
                }
                if (departmentPredicates.isEmpty()) {
                    predicates.add(cb.disjunction());
                } else {
                    predicates.add(cb.or(departmentPredicates.toArray(new javax.persistence.criteria.Predicate[0])));
                }
            }
            if (hasText(request.getLevel())) {
                predicates.add(cb.equal(root.get("level"), request.getLevel()));
            }
            if (request.getOwnerId() != null) {
                predicates.add(cb.equal(root.get("ownerId"), request.getOwnerId()));
            }
            if (hasText(request.getCourt())) {
                predicates.add(cb.like(root.get("court"), "%" + request.getCourt() + "%"));
            }
            if (startDate != null) {
                predicates.add(cb.greaterThanOrEqualTo(root.get("filingDate"), startDate));
            }
            if (endDate != null) {
                predicates.add(cb.lessThanOrEqualTo(root.get("filingDate"), endDate));
            }
            if (hasText(request.getKeyword())) {
                String keyword = "%" + request.getKeyword() + "%";
                javax.persistence.criteria.Predicate nameCondition = cb.like(root.get("caseName"), keyword);
                javax.persistence.criteria.Predicate numberCondition = cb.like(root.get("caseNumber"), keyword);
                predicates.add(cb.or(nameCondition, numberCondition));
            }
            if (hasText(request.getTag())) {
                predicates.add(cb.like(root.get("tags"), "%" + request.getTag() + "%"));
            }
            if (request.getArchived() != null) {
                if (request.getArchived()) {
                    predicates.add(cb.equal(root.get("status"), CaseStatus.ARCHIVED.getCode()));
                } else {
                    predicates.add(cb.notEqual(root.get("status"), CaseStatus.ARCHIVED.getCode()));
                }
            }
            if (request.getDeleted() != null) {
                predicates.add(cb.equal(root.get("deleted"), request.getDeleted()));
            } else {
                predicates.add(cb.equal(root.get("deleted"), false));
            }

            // 客户筛选：查询该客户关联的案件
            if (request.getClientId() != null) {
                predicates.add(cb.equal(root.get("clientId"), request.getClientId()));
            }

            return cb.and(predicates.toArray(new javax.persistence.criteria.Predicate[0]));
        };

        Page<Case> page = caseRepository.findAll(spec, pageable);

        // 转换为VO
        CaseActionPermissions actionPermissions = resolveCaseActionPermissions(currentUser);
        List<CaseListVO> records = page.getContent().stream()
                .map(caseEntity -> toListVO(caseEntity, currentUser, actionPermissions))
                .collect(Collectors.toList());

        return PageResult.of(
                (long) request.getPage(),
                (long) request.getSize(),
                page.getTotalElements(),
                records
        );
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }

    private LocalDate parseQueryDate(String value, String parameter) {
        if (!hasText(value)) {
            return null;
        }
        try {
            return LocalDate.parse(value.trim());
        } catch (DateTimeParseException e) {
            throw new InvalidParameterException(parameter, "日期格式应为 YYYY-MM-DD");
        }
    }

    /**
     * 开发管理员、主任和行政可查看全所案件；其他账号按案件关系或所属部门隔离。
     */
    private boolean isDevelopmentAdmin(User user) {
        return user != null && "admin".equals(user.getUsername());
    }

    private boolean hasAllCaseViewAccess(User user) {
        if (isDevelopmentAdmin(user)) {
            return true;
        }
        return isFirmDirector(user) || isAdministrativeUser(user);
    }

    private boolean isAdministrativeUser(User user) {
        String position = user == null ? null : user.getPosition();
        return position != null && position.startsWith("行政管理");
    }

    private boolean isDepartmentManager(User user) {
        String position = user == null ? null : user.getPosition();
        return "部门主管".equals(position)
                || "主管".equals(position)
                || "合伙人".equals(position);
    }

    private boolean isCaseFilingAdministrator(User user) {
        return userPermissionService.hasPermission(user, "CASE_FILING_MANAGE");
    }

    private List<Long> getDepartmentScopedUserIds(User currentUser) {
        if (currentUser.getDepartmentId() == null) {
            return Collections.singletonList(currentUser.getId());
        }
        return getActiveUserIdsByDepartment(currentUser.getDepartmentId(), currentUser.getId());
    }

    private List<Long> getActiveUserIdsByDepartment(Long departmentId) {
        return getActiveUserIdsByDepartment(departmentId, null);
    }

    private List<Long> getActiveUserIdsByDepartment(Long departmentId, Long fallbackUserId) {
        if (departmentId == null) {
            return fallbackUserId == null ? Collections.emptyList() : Collections.singletonList(fallbackUserId);
        }
        List<Long> userIds = userRepository.findByDepartmentId(departmentId).stream()
                .filter(user -> !Boolean.TRUE.equals(user.getDeleted()))
                .filter(user -> user.getStatus() == null || user.getStatus() == 1)
                .map(User::getId)
                .collect(Collectors.toList());
        if (fallbackUserId != null && !userIds.contains(fallbackUserId)) {
            userIds.add(fallbackUserId);
        }
        return userIds;
    }

    private List<Long> getDepartmentScopedCaseIds(List<Long> departmentUserIds) {
        if (departmentUserIds == null || departmentUserIds.isEmpty()) {
            return Collections.emptyList();
        }
        return caseMemberRepository.findByUserIdInAndDeletedFalse(departmentUserIds).stream()
                .map(CaseMember::getCaseId)
                .distinct()
                .collect(Collectors.toList());
    }

    /**
     * 判断用户是否有管理员角色
     */
    private boolean hasAdminRole(User user) {
        if (user == null || user.getId() == null) {
            return false;
        }
        List<UserRole> userRoles = userRoleRepository.findByUserId(user.getId());
        return userRoles.stream()
                .anyMatch(ur -> {
                    Role role = roleRepository.findById(ur.getRoleId()).orElse(null);
                    if (role == null) return false;
                    // 检查 roleCode 和 roleName，兼容数据库中的不同格式
                    return "ADMIN".equals(role.getRoleCode())
                            || "MANAGER".equals(role.getRoleCode())
                            || "管理员".equals(role.getRoleName())
                            || "主任".equals(role.getRoleName());
                });
    }

    private boolean isFirmDirector(User user) {
        return user != null
                && ("主任".equals(user.getPosition()) || hasAdminRole(user));
    }

    /**
     * 获取案件详情
     */
    @Transactional(readOnly = true)
    public CaseDetailVO getCaseDetail(Long caseId) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));

        CaseDetailVO vo = new CaseDetailVO();
        BeanUtils.copyProperties(caseEntity, vo);

        // 设置描述字段
        vo.setCaseTypeDesc(getCaseTypeDesc(caseEntity.getCaseType()));
        vo.setLevelDesc(getLevelDesc(caseEntity.getLevel()));
        vo.setStatusDesc(getStatusDesc(caseEntity.getStatus()));
        vo.setCloseStatusDesc(getCloseStatusDesc(caseEntity.getCloseStatus()));

        // 设置团队信息
        vo.setOwnerName(getUserName(caseEntity.getOwnerId()));
        vo.setCoOwners(getMembers(caseId, "CO_OWNER"));
        vo.setAssistants(getMembers(caseId, "ASSISTANT"));

        // 设置当事人列表
        List<com.lawfirm.vo.PartyVO> parties = partyService.getByCaseId(caseId);
        vo.setParties(parties);

        // 设置案件程序列表
        vo.setProcedures(caseProcedureService.getByCaseId(caseId));

        List<Long> clientIds = resolveClientIds(caseEntity, parties);
        vo.setClientIds(clientIds);
        vo.setClientName(resolvePrimaryClientName(caseEntity, clientIds, parties));
        vo.setConflictChecks(clientService.getConflictCheckRecordsByCaseId(caseId, null));

        // 设置阶段进度
        vo.setStageProgress(caseStageService.getStageProgress(caseId));

        return vo;
    }

    @Transactional(readOnly = true)
    public CaseDetailVO getCaseDetail(Long caseId, Long currentUserId) {
        assertCaseVisible(caseId, currentUserId);
        CaseDetailVO vo = getCaseDetail(caseId);
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        CaseActionPermissions actionPermissions = resolveCaseActionPermissions(currentUser);
        boolean manageable = isCaseManageableByUser(
                caseEntity, currentUser, actionPermissions.canManageFilingCases);
        boolean editable = manageable
                && !CaseStatus.CLOSED.getCode().equals(caseEntity.getStatus())
                && !CaseStatus.ARCHIVED.getCode().equals(caseEntity.getStatus());
        vo.setCanEdit(editable && actionPermissions.canEdit);
        vo.setCanDelete(manageable && actionPermissions.canDelete);
        vo.setCanArchive(manageable
                && CaseStatus.CLOSED.getCode().equals(caseEntity.getStatus())
                && actionPermissions.canArchive);
        vo.setCanChangeStatus(editable && actionPermissions.canEdit);
        vo.setConflictChecks(clientService.getConflictCheckRecordsByCaseId(caseId, currentUserId));
        return vo;
    }

    @Transactional(readOnly = true)
    public void assertCaseVisible(Long caseId, Long currentUserId) {
        if (!canAccessCase(caseId, currentUserId)) {
            throw new AccessDeniedException("无权访问非本部门案件");
        }
    }

    @Transactional(readOnly = true)
    public void assertCaseEditable(Long caseId, Long currentUserId) {
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        if (isCaseEditableByUser(caseId, currentUser)) {
            return;
        }
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        if ("CLOSED".equals(caseEntity.getStatus()) || "ARCHIVED".equals(caseEntity.getStatus())) {
            throw new InvalidParameterException("caseId", "案件已结案或归档，案件信息已锁定");
        }
        if (isAdministrativeUser(currentUser)) {
            throw new AccessDeniedException("行政管理账号可查看全案，但无权直接修改案件信息");
        }
        throw new AccessDeniedException("无权修改非本人或非本部门案件");
    }

    @Transactional(readOnly = true)
    public void assertCaseManageable(Long caseId, Long currentUserId) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        if (isCaseManageableByUser(caseEntity, currentUser)) {
            return;
        }
        if (isAdministrativeUser(currentUser)) {
            throw new AccessDeniedException("行政管理账号可查看全案，但无权执行该案件操作");
        }
        throw new AccessDeniedException("无权操作非本人或非本部门案件");
    }

    private boolean isCaseEditableByUser(Long caseId, User currentUser) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        if ("CLOSED".equals(caseEntity.getStatus()) || "ARCHIVED".equals(caseEntity.getStatus())) {
            return false;
        }
        return isCaseManageableByUser(caseEntity, currentUser);
    }

    private boolean isCaseManageableByUser(Case caseEntity, User currentUser) {
        if (isDevelopmentAdmin(currentUser) || isFirmDirector(currentUser)) {
            return true;
        }
        return isCaseManageableByUser(caseEntity, currentUser, isCaseFilingAdministrator(currentUser));
    }

    private boolean isCaseManageableByUser(
            Case caseEntity, User currentUser, boolean caseFilingAdministrator) {
        if (isDevelopmentAdmin(currentUser) || isFirmDirector(currentUser)
                || caseFilingAdministrator) {
            return true;
        }
        if (isAdministrativeUser(currentUser)) {
            return false;
        }
        if (Objects.equals(caseEntity.getOwnerId(), currentUser.getId())) {
            return true;
        }
        List<CaseMember> members = caseMemberRepository.findByCaseIdAndDeletedFalse(caseEntity.getId());
        if (members.stream().map(CaseMember::getUserId).anyMatch(currentUser.getId()::equals)) {
            return true;
        }
        if (!isDepartmentManager(currentUser) || currentUser.getDepartmentId() == null) {
            return false;
        }
        User owner = userRepository.findById(caseEntity.getOwnerId()).orElse(null);
        if (owner != null && Objects.equals(owner.getDepartmentId(), currentUser.getDepartmentId())) {
            return true;
        }
        return members.stream()
                .map(CaseMember::getUserId)
                .map(userRepository::findById)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .anyMatch(user -> Objects.equals(user.getDepartmentId(), currentUser.getDepartmentId()));
    }

    @Transactional(readOnly = true)
    public boolean canAccessCase(Long caseId, Long currentUserId) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        if (hasAllCaseViewAccess(currentUser)) {
            return true;
        }
        if (isAdministrativeUser(currentUser)) {
            return true;
        }
        if (Objects.equals(caseEntity.getOwnerId(), currentUserId)) {
            return true;
        }
        boolean currentUserIsMember = caseMemberRepository.findByCaseIdAndDeletedFalse(caseId).stream()
                .map(CaseMember::getUserId)
                .anyMatch(userId -> Objects.equals(userId, currentUserId));
        if (currentUserIsMember) {
            return true;
        }
        if (!isDepartmentManager(currentUser) || currentUser.getDepartmentId() == null) {
            return false;
        }
        User owner = userRepository.findById(caseEntity.getOwnerId()).orElse(null);
        if (owner != null && Objects.equals(owner.getDepartmentId(), currentUser.getDepartmentId())) {
            return true;
        }
        return caseMemberRepository.findByCaseIdAndDeletedFalse(caseId).stream()
                .map(CaseMember::getUserId)
                .map(userRepository::findById)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .anyMatch(user -> Objects.equals(user.getDepartmentId(), currentUser.getDepartmentId()));
    }

    private List<Long> resolveClientIds(Case caseEntity, List<com.lawfirm.vo.PartyVO> parties) {
        if (caseEntity.getClientId() != null) {
            return Collections.singletonList(caseEntity.getClientId());
        }

        if (parties == null || parties.isEmpty()) {
            return Collections.emptyList();
        }

        return parties.stream()
                .filter(p -> Boolean.TRUE.equals(p.getIsClient()))
                .map(com.lawfirm.vo.PartyVO::getName)
                .filter(this::hasText)
                .map(name -> clientRepository.findByClientNameAndDeletedFalse(name).map(Client::getId).orElse(null))
                .filter(Objects::nonNull)
                .distinct()
                .collect(Collectors.toList());
    }

    private String resolvePrimaryClientName(
            Case caseEntity,
            List<Long> clientIds,
            List<com.lawfirm.vo.PartyVO> parties) {
        if (clientIds != null && !clientIds.isEmpty()) {
            String name = clientRepository.findById(clientIds.get(0))
                    .map(Client::getClientName)
                    .filter(this::hasText)
                    .orElse(null);
            if (hasText(name)) {
                return name;
            }
        }
        if ("CONSULTANT".equals(caseEntity.getCaseType()) && hasText(caseEntity.getConsultantUnitName())) {
            return caseEntity.getConsultantUnitName();
        }
        if (parties == null) {
            return null;
        }
        return parties.stream()
                .filter(p -> Boolean.TRUE.equals(p.getIsClient()))
                .map(com.lawfirm.vo.PartyVO::getName)
                .filter(this::hasText)
                .findFirst()
                .orElse(null);
    }

    /**
     * 删除案件（逻辑删除）
     */
    @Transactional(rollbackFor = Exception.class)
    public void deleteCase(Long caseId) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));

        caseEntity.setDeleted(true);
        caseRepository.save(caseEntity);

        // 记录动态
        caseTimelineService.createSystemTimeline(
                caseId,
                "CASE_DELETED",
                "案件已删除"
        );
    }

    /**
     * 恢复已删除的案件
     */
    @Transactional(rollbackFor = Exception.class)
    public void restoreCase(Long caseId) {
        Case caseEntity = caseRepository.findById(caseId)
                .orElseThrow(() -> new ResourceNotFoundException("案件", caseId));

        if (!caseEntity.getDeleted()) {
            throw new InvalidParameterException("caseId", "该案件未被删除，无需恢复");
        }

        caseEntity.setDeleted(false);
        caseRepository.save(caseEntity);

        // 记录动态
        caseTimelineService.createSystemTimeline(
                caseId,
                "CASE_RESTORED",
                "案件已从回收站恢复"
        );
    }

    /**
     * 归档案件
     */
    @Transactional(rollbackFor = Exception.class)
    public void archiveCase(Long caseId, String archiveLocation) {
        throw new InvalidParameterException("archiveWorkflow", "直接归档已停用，请在案件详情的智能归档中发起归档任务");
    }

    /**
     * 查重检查
     * PRD要求（228行）：按案件名称和案号查重
     */
    public List<CaseListVO> checkDuplicate(String name, String caseNumber, Long currentUserId) {
        User currentUser = userRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("用户", currentUserId));
        List<Case> duplicates = new ArrayList<>();

        if (name != null && !name.trim().isEmpty()) {
            duplicates.addAll(caseRepository.findByCaseNameContainingAndDeletedFalse(name));
        }

        if (caseNumber != null && !caseNumber.trim().isEmpty()) {
            List<Case> byNumber = caseRepository.findAllByCaseNumberAndDeletedFalse(caseNumber);
            duplicates.addAll(byNumber);
        }

        // 去重
        duplicates = duplicates.stream()
                .distinct()
                .filter(c -> canAccessCase(c.getId(), currentUserId))
                .collect(Collectors.toList());

        CaseActionPermissions actionPermissions = resolveCaseActionPermissions(currentUser);
        return duplicates.stream()
                .map(caseEntity -> toListVO(caseEntity, currentUser, actionPermissions))
                .collect(Collectors.toList());
    }

    /**
     * 搜索法院（用于案件筛选的法院选择器）
     */
    public List<String> searchCourts(String keyword) {
        if (keyword == null || keyword.trim().isEmpty()) {
            // 如果没有关键词，返回所有不重复的法院
            return caseRepository.findDistinctCourts();
        } else {
            // 如果有关键词，进行模糊搜索
            return caseRepository.findCourtsByKeyword(keyword);
        }
    }

    /**
     * 自动生成案件名称
     */
    public String autoGenerateName(CaseCreateRequest request) {
        List<PartyDTO> parties = request.getParties();
        if ("CRIMINAL".equals(request.getCaseType()) && hasText(request.getSuspectName())) {
            return request.getSuspectName() + (hasText(request.getCaseReason()) ? request.getCaseReason() : "刑事案件");
        }
        if ("CONSULTANT".equals(request.getCaseType())) {
            String client = hasText(request.getConsultantUnitName())
                    ? request.getConsultantUnitName()
                    : firstClientName(parties, "顾问单位");
            String year = request.getServiceStartDate() == null ? "" : request.getServiceStartDate().getYear() + "年度";
            return client + year + (hasText(request.getBusinessType()) ? request.getBusinessType() : "法律顾问");
        }
        if ("NON_LITIGATION".equals(request.getCaseType())) {
            String client = firstClientName(parties, "当事人");
            return client + (hasText(request.getCaseReason()) ? request.getCaseReason() : "非诉案件");
        }
        if (parties == null || parties.isEmpty()) {
            return "未命名案件";
        }

        String plaintiff = parties.stream()
                .filter(p -> "PLAINTIFF".equals(p.getPartyRole()) || "APPLICANT".equals(p.getPartyRole()))
                .map(PartyDTO::getName)
                .findFirst()
                .orElse("原告");

        String defendant = parties.stream()
                .filter(p -> "DEFENDANT".equals(p.getPartyRole()) || "RESPONDENT".equals(p.getPartyRole()))
                .map(PartyDTO::getName)
                .findFirst()
                .orElse("被告");

        return plaintiff + " Vs " + defendant;
    }

    private String firstClientName(List<PartyDTO> parties, String fallback) {
        if (parties == null || parties.isEmpty()) return fallback;
        return parties.stream()
                .filter(p -> Boolean.TRUE.equals(p.getIsClient()))
                .map(PartyDTO::getName)
                .filter(this::hasText)
                .findFirst()
                .orElseGet(() -> parties.stream().map(PartyDTO::getName).filter(this::hasText).findFirst().orElse(fallback));
    }

    public String autoGenerateDraftNumber(String caseType) {
        return "LS-" + java.time.Year.now().getValue() + "-" + getCaseTypeCode(caseType) + "-" + System.currentTimeMillis();
    }

    /**
     * 自动生成案件编号
     */
    public String autoGenerateNumber(String caseType) {
        String year = String.valueOf(java.time.Year.now().getValue());
        String typeCode = getCaseTypeCode(caseType);

        // 查询当年该类型的案件数量
        long count = caseRepository.countByCaseTypeAndDeletedFalse(caseType);

        // 生成格式：年份-类型代码-序号
        return String.format("%s-%s-%04d", year, typeCode, count + 1);
    }

    // 辅助方法
    private CaseListVO toListVO(
            Case caseEntity, User currentUser, CaseActionPermissions actionPermissions) {
        CaseListVO vo = new CaseListVO();
        BeanUtils.copyProperties(caseEntity, vo);
        vo.setCaseTypeDesc(getCaseTypeDesc(caseEntity.getCaseType()));
        vo.setStatusDesc(getStatusDesc(caseEntity.getStatus()));
        vo.setLevelDesc(getLevelDesc(caseEntity.getLevel()));
        vo.setOwnerName(getUserName(caseEntity.getOwnerId()));
        vo.setNextHearingDate(caseEntity.getHearingDate());

        boolean manageable = isCaseManageableByUser(
                caseEntity, currentUser, actionPermissions.canManageFilingCases);
        boolean locked = CaseStatus.CLOSED.getCode().equals(caseEntity.getStatus())
                || CaseStatus.ARCHIVED.getCode().equals(caseEntity.getStatus());
        vo.setCanEdit(manageable && !locked && actionPermissions.canEdit);
        vo.setCanDelete(manageable && actionPermissions.canDelete);
        vo.setCanArchive(manageable
                && CaseStatus.CLOSED.getCode().equals(caseEntity.getStatus())
                && actionPermissions.canArchive);

        // 获取当事人信息
        List<com.lawfirm.vo.PartyVO> parties = partyService.getByCaseId(caseEntity.getId());
        vo.setParties(summarizeParties(caseEntity, parties));

        return vo;
    }

    private CaseActionPermissions resolveCaseActionPermissions(User currentUser) {
        return new CaseActionPermissions(
                userPermissionService.hasPermission(currentUser, "CASE_EDIT"),
                userPermissionService.hasPermission(currentUser, "CASE_DELETE"),
                userPermissionService.hasPermission(currentUser, "CASE_ARCHIVE"),
                userPermissionService.hasPermission(currentUser, "CASE_FILING_MANAGE")
        );
    }

    private static final class CaseActionPermissions {
        private final boolean canEdit;
        private final boolean canDelete;
        private final boolean canArchive;
        private final boolean canManageFilingCases;

        private CaseActionPermissions(
                boolean canEdit, boolean canDelete, boolean canArchive, boolean canManageFilingCases) {
            this.canEdit = canEdit;
            this.canDelete = canDelete;
            this.canArchive = canArchive;
            this.canManageFilingCases = canManageFilingCases;
        }
    }

    private String getUserName(Long userId) {
        return userRepository.findById(userId)
                .map(User::getRealName)
                .orElse("未知");
    }

    private String summarizeParties(Case caseEntity, List<com.lawfirm.vo.PartyVO> parties) {
        if ("CONSULTANT".equals(caseEntity.getCaseType())) {
            String consultantUnit = hasText(caseEntity.getConsultantUnitName())
                    ? caseEntity.getConsultantUnitName()
                    : parties == null ? "" : parties.stream()
                            .filter(p -> hasText(p.getName()))
                            .map(com.lawfirm.vo.PartyVO::getName)
                            .findFirst()
                            .orElse("");
            return hasText(consultantUnit) ? "顾问单位：" + consultantUnit : "-";
        }
        if (parties == null || parties.isEmpty()) return "-";
        if ("CIVIL".equals(caseEntity.getCaseType())) {
            String left = firstPartyByRoles(parties, "PLAINTIFF", "APPELLANT", "APPLICANT");
            String right = firstPartyByRoles(parties, "DEFENDANT", "APPELLEE", "RESPONDENT");
            if (hasText(left) && hasText(right)) return left + " vs " + right;
        }
        return parties.stream().limit(3)
                .map(p -> (hasText(p.getPartyRoleDesc()) ? p.getPartyRoleDesc() + "：" : "") + p.getName())
                .collect(Collectors.joining("；"));
    }

    private String firstPartyByRoles(List<com.lawfirm.vo.PartyVO> parties, String... roles) {
        Set<String> accepted = new HashSet<>(Arrays.asList(roles));
        return parties.stream().filter(p -> accepted.contains(p.getPartyRole()))
                .map(com.lawfirm.vo.PartyVO::getName).filter(this::hasText).findFirst().orElse("");
    }

    private List<CaseDetailVO.MemberVO> getMembers(Long caseId, String memberType) {
        List<CaseMember> members = caseMemberService.getByCaseIdAndType(caseId, memberType);
        return members.stream()
                .map(m -> {
                    CaseDetailVO.MemberVO vo = new CaseDetailVO.MemberVO();
                    vo.setId(m.getUserId());
                    vo.setName(getUserName(m.getUserId()));
                    vo.setRole(memberType);
                    return vo;
                })
                .collect(Collectors.toList());
    }

    private String getCaseTypeDesc(String type) {
        if (type == null) return null;
        switch (type) {
            case "CIVIL": return "民事诉讼";
            case "COMMERCIAL": return "商事";
            case "ARBITRATION": return "商事仲裁";
            case "CRIMINAL": return "刑事";
            case "ADMINISTRATIVE": return "行政";
            case "NON_LITIGATION": return "非诉专项";
            case "CONSULTANT": return "法律顾问";
            default: return type;
        }
    }

    private String getLevelDesc(String level) {
        if (level == null) return null;
        switch (level) {
            case "IMPORTANT": return "重要";
            case "GENERAL": return "一般";
            case "MINOR": return "次要";
            default: return level;
        }
    }

    private String getStatusDesc(String status) {
        if (status == null) return null;
        switch (status) {
            case "CONSULTATION": return "咨询";
            case "PENDING_APPROVAL": return "待审批";
            case "FILING_REJECTED": return "立案驳回";
            case "SIGNED": return "签约";
            case "PENDING_FILING": return "待立案";
            case "ACTIVE": return "审理中";
            case "CLOSED": return "结案";
            case "ARCHIVED": return "归档";
            default: return status;
        }
    }

    private String getCloseStatusDesc(String status) {
        if (status == null) return null;
        switch (status) {
            case "ACHIEVED": return "达成诉求";
            case "PARTIALLY_ACHIEVED": return "部分达成";
            case "NOT_ACHIEVED": return "未达成";
            case "NOT_COMMISSIONED": return "未委托";
            case "TERMINATED": return "终止";
            default: return status;
        }
    }

    private String getCaseTypeCode(String caseType) {
        if (caseType == null) return "X";
        switch (caseType) {
            case "CIVIL": return "M";
            case "COMMERCIAL": return "S";
            case "ARBITRATION": return "R";
            case "CRIMINAL": return "C";
            case "ADMINISTRATIVE": return "A";
            case "NON_LITIGATION": return "N";
            case "CONSULTANT": return "G";
            default: return "X";
        }
    }

    /**
     * 同步创建客户
     * PRD要求（第246行）：勾选"同步创建客户"复选框后自动在客户库创建
     */
    private void syncPartiesToClients(List<com.lawfirm.dto.PartyDTO> parties, Long caseId, Long userId) {
        if (parties == null || parties.isEmpty()) {
            return;
        }

        for (com.lawfirm.dto.PartyDTO partyDTO : parties) {
            // 只有当isClient=true且syncToClient=true时才同步创建
            if (partyDTO.getIsClient() != null && partyDTO.getIsClient()
                && partyDTO.getSyncToClient() != null && partyDTO.getSyncToClient()) {

                try {
                    // 检查客户是否已存在（根据名称）
                    if (clientRepository.existsByClientNameAndDeletedIsFalse(partyDTO.getName())) {
                        log.info("客户已存在，跳过创建：{}", partyDTO.getName());
                        continue;
                    }

                    // 创建ClientDTO
                    com.lawfirm.dto.ClientDTO clientDTO = new com.lawfirm.dto.ClientDTO();
                    clientDTO.setClientType("INDIVIDUAL".equals(partyDTO.getPartyType()) ? "个人" : "企业");
                    clientDTO.setClientRelationship("委托人");
                    clientDTO.setClientRole(partyDTO.getPartyRole());
                    clientDTO.setClientName(partyDTO.getName());
                    clientDTO.setGender(partyDTO.getGender());
                    clientDTO.setIdCard(partyDTO.getIdCard());
                    clientDTO.setCreditCode(partyDTO.getCreditCode());
                    clientDTO.setPhone(partyDTO.getPhone());
                    clientDTO.setAddress(partyDTO.getAddress());
                    clientDTO.setLegalRepresentative(partyDTO.getLegalRepresentative());
                    clientDTO.setStatus("ACTIVE");
                    clientDTO.setSource("CASE_SYNC");
                    clientDTO.setNotes("从案件ID=" + caseId + "同步创建");
                    clientDTO.setSourceUserIds(String.valueOf(userId));
                    clientDTO.setClientOwnerIds(String.valueOf(userId));
                    userRepository.findById(userId).map(User::getDepartmentId).ifPresent(clientDTO::setDepartmentId);

                    // 创建客户
                    com.lawfirm.dto.ClientDTO createdClient = clientService.createClient(clientDTO, userId);
                    log.info("同步创建客户成功：案件ID={}, 客户ID={}, 客户名称={}",
                             caseId, createdClient.getId(), createdClient.getClientName());
                } catch (Exception e) {
                    // 如果客户已存在或其他错误，记录日志但不中断案件创建流程
                    log.warn("同步创建客户失败：案件ID={}, 当事人名称={}, 错误={}",
                             caseId, partyDTO.getName(), e.getMessage());
                }
            }
        }
    }

    /**
     * 创建审限届满待办事项
     * PRD要求：审限时间录入后自动生成审限届满待办
     */
    private void createDeadlineTodo(Case caseEntity) {
        log.info("[DEBUG] 开始创建审限待办：案件ID={}, 案件名={}, 审限={}, ownerId={}",
                caseEntity.getId(), caseEntity.getCaseName(), caseEntity.getDeadlineDate(), caseEntity.getOwnerId());
        try {
            TodoDTO todoDTO = new TodoDTO();
            todoDTO.setTitle("【审限届满】" + caseEntity.getCaseName());
            todoDTO.setDescription("案件审限即将届满，请及时处理相关事宜。案号：" + caseEntity.getCaseNumber());
            todoDTO.setPriority("HIGH");
            todoDTO.setDueDate(caseEntity.getDeadlineDate().atStartOfDay());
            todoDTO.setStatus("PENDING");
            todoDTO.setAssigneeId(caseEntity.getOwnerId());
            todoDTO.setCaseId(caseEntity.getId());
            todoDTO.setReminder(true);

            TodoDTO created = todoService.createTodo(todoDTO, caseEntity.getOwnerId());
            log.info("自动创建审限届满待办成功：案件ID={}, 待办ID={}, 标题={}",
                    caseEntity.getId(), created.getId(), created.getTitle());
        } catch (Exception e) {
            log.error("创建审限届满待办失败：案件ID={}, 错误={}", caseEntity.getId(), e.getMessage(), e);
            throw new RuntimeException("创建审限待办失败: " + e.getMessage(), e);
        }
    }

    // ==================== 批量操作 ====================

    /**
     * 批量结案
     */
    @Transactional
    public void batchCloseCases(List<Long> caseIds, Long operatorId) {
        List<Case> cases = requireBatchCases(caseIds);
        for (Case caseEntity : cases) {
            assertCaseEditable(caseEntity.getId(), operatorId);
            if (!CaseStatus.ACTIVE.getCode().equals(caseEntity.getStatus())) {
                throw new InvalidParameterException("caseIds", "只有审理中的案件可以结案：" + caseEntity.getCaseName());
            }
        }
        for (Case caseEntity : cases) {
            caseEntity.setStatus(CaseStatus.CLOSED.getCode());
            caseEntity.setCloseDate(LocalDate.now());
            caseEntity.setUpdatedAt(LocalDateTime.now());
            caseTimelineService.createSystemTimeline(
                    caseEntity.getId(),
                    "CASE_CLOSED",
                    "案件已通过批量操作结案"
            );
        }

        caseRepository.saveAll(cases);
        log.info("Batch close cases completed: count={}, operator={}", caseIds.size(), operatorId);
    }

    /**
     * 批量归档
     */
    @Transactional
    public void batchArchiveCases(List<Long> caseIds, String archiveLocation, Long operatorId) {
        throw new InvalidParameterException("archiveWorkflow", "批量直接归档已停用，请逐案完成智能归档与行政复核");
    }

    /**
     * 批量删除（软删除）
     */
    @Transactional
    public void batchDeleteCases(List<Long> caseIds, Long operatorId) {
        List<Case> cases = requireBatchCases(caseIds);
        for (Case caseEntity : cases) {
            assertCaseManageable(caseEntity.getId(), operatorId);
        }
        for (Case caseEntity : cases) {
            caseEntity.setDeleted(true);
            caseEntity.setUpdatedAt(LocalDateTime.now());
            caseTimelineService.createSystemTimeline(
                    caseEntity.getId(),
                    "CASE_DELETED",
                    "案件已通过批量操作删除"
            );
        }

        caseRepository.saveAll(cases);
        log.info("Batch delete cases completed: count={}, operator={}", caseIds.size(), operatorId);
    }

    /**
     * 批量修改主办律师
     */
    @Transactional
    public void batchChangeOwner(List<Long> caseIds, Long newOwnerId, Long operatorId) {
        if (newOwnerId == null) {
            throw new InvalidParameterException("ownerId", "新承办人不能为空");
        }

        User newOwner = userRepository.findById(newOwnerId)
                .filter(user -> !Boolean.TRUE.equals(user.getDeleted()) && user.getStatus() != null && user.getStatus() == 1)
                .orElseThrow(() -> new ResourceNotFoundException("有效用户", newOwnerId));

        List<Case> cases = requireBatchCases(caseIds);
        for (Case caseEntity : cases) {
            assertCaseEditable(caseEntity.getId(), operatorId);
        }
        for (Case caseEntity : cases) {
            Long previousOwnerId = caseEntity.getOwnerId();
            caseEntity.setOwnerId(newOwnerId);
            caseEntity.setUpdatedAt(LocalDateTime.now());
            caseTimelineService.createSystemTimeline(
                    caseEntity.getId(),
                    "OWNER_CHANGED",
                    String.format("承办人由「%s」变更为「%s」",
                            getUserName(previousOwnerId), newOwner.getRealName())
            );
        }

        caseRepository.saveAll(cases);
        log.info("Batch change owner completed: count={}, newOwner={}, operator={}", caseIds.size(), newOwnerId, operatorId);
    }

    private List<Case> requireBatchCases(List<Long> caseIds) {
        if (caseIds == null || caseIds.isEmpty()) {
            throw new InvalidParameterException("caseIds", "案件列表不能为空");
        }
        List<Long> distinctIds = caseIds.stream().filter(Objects::nonNull).distinct().collect(Collectors.toList());
        if (distinctIds.isEmpty()) {
            throw new InvalidParameterException("caseIds", "案件列表不能为空");
        }
        List<Case> cases = caseRepository.findAllById(distinctIds);
        if (cases.size() != distinctIds.size()) {
            throw new InvalidParameterException("caseIds", "批量操作中包含不存在的案件");
        }
        return cases;
    }
}
