package com.lawfirm.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@RequiredArgsConstructor
public class KnowledgeArticleInitService {

    private final JdbcTemplate jdbcTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void initKnowledgeArticleTable() {
        try {
            // 检查表是否已存在
            Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'knowledge_article'",
                Integer.class
            );

            if (count != null && count > 0) {
                ensureKnowledgeArticleColumns();
                log.info("KnowledgeArticle table already exists, ensured required columns");
                return;
            }

            log.info("Creating KnowledgeArticle table...");

            // 使用未引用标识符，兼容H2自动大写和PostgreSQL自动小写规则。
            String createTableSql =
                "CREATE TABLE knowledge_article (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "title VARCHAR(200) NOT NULL," +
                "article_type VARCHAR(20) NOT NULL," +
                "knowledge_source VARCHAR(30) DEFAULT 'FIRM_KNOWLEDGE'," +
                "category VARCHAR(50), tags VARCHAR(500), summary VARCHAR(1000), content TEXT," +
                "attachment_path VARCHAR(500), view_count INTEGER DEFAULT 0, like_count INTEGER DEFAULT 0," +
                "is_top BOOLEAN DEFAULT FALSE, is_public BOOLEAN DEFAULT TRUE," +
                "knowledge_eligible BOOLEAN DEFAULT TRUE, index_status VARCHAR(30) DEFAULT 'PENDING'," +
                "author_id BIGINT, author_name VARCHAR(50), updater_id BIGINT," +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "deleted BOOLEAN DEFAULT FALSE" +
                ")";

            jdbcTemplate.execute(createTableSql);
            log.info("KnowledgeArticle table created successfully");

        } catch (Exception e) {
            log.error("Failed to initialize KnowledgeArticle table", e);
        }
    }

    private void ensureKnowledgeArticleColumns() {
        String[] alterStatements = {
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS knowledge_source VARCHAR(30) DEFAULT 'FIRM_KNOWLEDGE'",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS summary VARCHAR(1000)",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS attachment_path VARCHAR(500)",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS like_count INTEGER DEFAULT 0",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS is_top BOOLEAN DEFAULT FALSE",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS knowledge_eligible BOOLEAN DEFAULT TRUE",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS index_status VARCHAR(30) DEFAULT 'PENDING'",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS author_id BIGINT",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS author_name VARCHAR(50)",
                "ALTER TABLE knowledge_article ADD COLUMN IF NOT EXISTS updater_id BIGINT"
        };

        for (String sql : alterStatements) {
            try {
                jdbcTemplate.execute(sql);
            } catch (Exception e) {
                log.warn("Ensure knowledge_article column skipped: {}", e.getMessage());
            }
        }
    }
}
